site_name: Dartmouth Brain Imaging Center Handbook vX.X.X-dev
theme:
    name: material
    custom_dir: theme_customizations/
    favicon: images/favicon.png
    logo: images/logo.png
    palette:
        primary: 'light green'
        accent: 'light green'
extra_javascript:
    - js/jquery-3.4.1.min.js
markdown_extensions:
    - toc:
        anchorlink: true
plugins:
    - search
docs_dir: 'src'
use_directory_urls: false
nav:
    - Introduction: 01-introduction.md
    - Useful basics:
      - Shell: TODO.md
      - SSH: TODO.md
      - Containers: containers.md
      - DataLad: datalad.md
      - PyBIDS: TODO.md
    - A new study:
        - Policies & procedures: https://www.dartmouth.edu/dbic/
        - JEDCap: TODO.md
        - Experimental design: TODO.md
        - Pre-registration: TODO.md
    - Stimuli/Behavioral: stimuli.md
    - MRI:
        - Overview: mri/overview.md
        - ReproIn naming convention: mri/reproin.md
        - Siemens Console Walkthrough: mri/walkthrough-1.md
        - MR Safety: mri/safety.md
        - Data access:
            - DICOMs: TODO.md
            - BIDS: TODO.md
        - Data processing:
            - QA: TODO.md
            - Preprocessing: TODO.md
            - Analysis: TODO.md
    - EEG: TODO.md
    - MRS: TODO.md
    - Computing resources:
      - Discovery HPC: discovery.md
    - Publishing:
        - Datasets: TODO.md
        - Papers:
            - Data descriptor: TODO.md
            - Study paper(s): TODO.md
    - Appendix:
        - Contributors: 99-appendices/01-contributors.md
        - Licenses: 99-appendices/02-licenses.md
    - Changelog: CHANGES.md
    - Contributing: CONTRIBUTING.md
    - DBIC website: http://dartmouth.edu/dbic
    - DBIC GitHub: http://github.com/dbic
